services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./momo_payment_test_be/api/api
      dockerfile: Dockerfile
    container_name: backend_api
    env_file:
      - ./momo_payment_test_be/api/api/.env.docker
    ports:
      - "8002:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./momo_payment_test
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL} 
    container_name: frontend_app
    ports:
      - "5173:80"
    env_file:
      - ./momo_payment_test/.env.docker
    depends_on:
      - backend

volumes:
  db_data: